### ISSUE TITLE
make all failed

### ISSUE THREAD

**Issue by nrth3rnlb** [longsleep/bcmwl-ubuntu#1]
```
$ make  
KBUILD_NOPEDANTIC=1 make -C /lib/modules/`uname -r`/build M=`pwd`
make[1]: Entering directory '/usr/src/linux-headers-3.19.0-15-generic'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
make[2]: *** No rule to make target '/home/aboettger/tmp/bcmwl-ubuntu/src/shared/linux_osl.o', needed by '/home/aboettger/tmp/bcmwl-ubuntu/wl.o'.  Stop.
Makefile:1394: recipe for target '_module_/home/aboettger/tmp/bcmwl-ubuntu' failed
make[1]: *** [_module_/home/aboettger/tmp/bcmwl-ubuntu] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.19.0-15-generic'
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by kenjungclaus** [comment]
Same here with 4.0.0-040000-generic. Details: http://askubuntu.com/questions/612566/how-to-compile-bcmwl-ubuntu
@aboettger If you need a working driver immediately, you can use the bcmwl-kernel-source package from the repository. At least for me it worked with 3.19.

**Comment by longsleep** [comment]
Guys this repository is ubuntu packaging. So you should build the package and install it. It then builds the module with the kernel patches required for your particular kernel version. I See that the readme needs some work :-)

**Comment by kenjungclaus** [comment]
Do you mean by `bzr`? Then apologize my ignorance. It would be great if you could describe the procedure in the readme. Thanks!

**Comment by longsleep** [comment]
No not by bzr. dpkg-buildpackage is your friend. This is a git repository with all the gear for git-buildpackage - so usw gbp. I will update the readme.

**Comment by nrth3rnlb** [comment]
```
$ gbp buildpackage -b -uc
[...]
dpkg-deb: building package `bcmwl-kernel-source' in `../bcmwl-kernel-source_6.30.223.248+bdcom-1longsleep0_amd64.deb'.
 dpkg-genchanges -b >../bcmwl_6.30.223.248+bdcom-1longsleep0_amd64.changes
dpkg-genchanges: binary-only upload (no source code included)
 dpkg-source -i -I --after-build bcmwl-ubuntu
dpkg-buildpackage: binary-only upload (no source included)
Now running lintian...
E: bcmwl-kernel-source: unstripped-binary-or-object usr/src/bcmwl-6.30.223.248+bdcom/lib/wlc_hybrid.o_shipped_x86_64
E: bcmwl-kernel-source: helper-templates-in-copyright
W: bcmwl-kernel-source: executable-not-elf-or-script usr/src/bcmwl-6.30.223.248+bdcom/lib/LICENSE.txt
Finished running lintian.
Now signing dsc file...
 signfile bcmwl_6.30.223.248+bdcom-1longsleep0.dsc Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
gpg: skipped "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>": secret key not available
gpg: /tmp/debsign.cOYU0daw/bcmwl_6.30.223.248+bdcom-1longsleep0.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1305:
running debsign failed
gbp:error: 'debuild -i -I -b -uc' failed: it exited with 29
```

**Comment by kenjungclaus** [comment]
@aboettger We should better wait till longsleep updated the readme. ;-)
For your interest: I don't know if it was a good idea or if e.g. all patches are included but using `dpkg-buildpackage` created the package for me without errors. Unfortunately I can't test the deb file right now.

**Comment by nrth3rnlb** [comment]
@lum3n I wanted to give you a good [answer](http://askubuntu.com/q/612566/367165). :)

**Comment by kenjungclaus** [comment]
@aboettger Thank you, I really appreciate your help. Nevertheless you should edit your post on askubuntu.com because it's not working that way, I guess (in case it's not a real flaw).

**Comment by longsleep** [comment]
@aboettger your package did build fine but you try to sign with the Ubuntu release key which does obviously fail. Try adding -us (to not sign the source too) or provide your own GPG key id with -k$KEY. Still as build worked fine you should find the package one directory up.

**Comment by longsleep** [comment]
Readme was updated with build instructions.

**Comment by kenjungclaus** [comment]
I just wanted to say thank you for your fast help and the patch in general.

**Comment by longsleep** [comment]
@lum3n You are welcome.
