### ISSUE TITLE
Issue with kernel 4.2

### ISSUE THREAD

**Issue by brunano21** [longsleep/bcmwl-ubuntu#10]
Hello, 
I just installed the kernel 4.2 [4.2.0-040200-generic_4.2.0-040200.201508301530]
and I got this problem:

Get:1 http://ppa.launchpad.net/longsleep/bcmwl/ubuntu/ trusty/main bcmwl-kernel-source amd64 6.30.223.248+bdcom-1longsleep1 [1,514 kB]
Fetched 1,514 kB in 2s (741 kB/s)  
(Reading database ... 296970 files and directories currently installed.)
Preparing to unpack .../bcmwl-kernel-source_6.30.223.248+bdcom-1longsleep1_amd64.deb ...
Removing all DKMS Modules
Done.
Unpacking bcmwl-kernel-source (6.30.223.248+bdcom-1longsleep1) over (6.30.223.248+bdcom-0ubuntu0.1) ...
Setting up bcmwl-kernel-source (6.30.223.248+bdcom-1longsleep1) ...
Loading new bcmwl-6.30.223.248+bdcom DKMS files...
Building for 3.19.0-28-generic and 4.2.0-040200-generic
Building for architecture x86_64
Building initial module for 3.19.0-28-generic
Done.

wl:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/3.19.0-28-generic/updates/dkms/

depmod....

DKMS: install completed.
Building initial module for 4.2.0-040200-generic
ERROR (dkms apport): kernel package linux-headers-4.2.0-040200-generic is not supported
Error! Bad return status for module build on kernel: 4.2.0-040200-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.103ubuntu4.2) ...
update-initramfs: Generating /boot/initrd.img-4.2.0-040200-generic

Am I missing something?
Thanks a lot!

**Comment by brunano21** [comment]
cat /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log
DKMS make.log for bcmwl-6.30.223.248+bdcom for kernel 4.2.0-040200-generic (x86_64)
Fri Sep 11 21:31:31 IST 2015
make: Entering directory `/usr/src/linux-headers-4.2.0-040200-generic'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/built-in.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_linux.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_iw.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o
  LD [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/wl.o
  Building modules, stage 2.
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  MODPOST 1 modules
FATAL: modpost: GPL-incompatible module wl.ko uses GPL-only symbol 'flush_workqueue'
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2
make: Leaving directory`/usr/src/linux-headers-4.2.0-040200-generic'

**Comment by kri4er** [comment]
Hello, brunano21!
It looks like you have a really simple bug. All you need is to go to the repository longsleep/bcmwl-ubuntu and follow the instructions, with one little change.
After command git clone, you should go to the 
bcmwl-ubuntu/bcmwl-ubuntu-master/debian/patches
 folder, then patches folder and make next changes in the 0001-MODULE_LICENSE.patch
Instead of MODULE_LICENSE("something")
Write
MODULE_LICENSE("GPL")
then continue steps like in turorial.
You can have some git related issues, or packages problems but they are all easy to fix.
If you have any problems with buid, ask, and I will help.

**Comment by brunano21** [comment]
Hi @kri4er unfortunately I cannot try this again, because I uninstalled the 4.2 after few problems I encountered. However, if in future I'll do it again, I'll keep in mind this solution. Thanks for the reply. 
However, I was using the PPA package, instead of building it.

Thanks again!
