### ISSUE TITLE
Can't compile on trusty (mint 17.2) with Kernel 4.2.5 from kernel ppa

### ISSUE THREAD

**Issue by derjohn** [longsleep/bcmwl-ubuntu#12]
Hello,
I use the the pre-build mainline kernels from http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.2.5-wily/ .
Since 4.2.5 they are called -wily, not unstable.

sudo apt-get install bcmwl-kernel-source from the longsleep ppa give a compile error on 4.2.5 (on 4.2.3 it worked):

```
Building initial module for 4.2.5-040205-generic
Error! Bad return status for module build on kernel: 4.2.5-040205-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
dpkg: Fehler beim Bearbeiten des Paketes bcmwl-kernel-source (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 10 zurück
Fehler traten auf beim Bearbeiten von:
 bcmwl-kernel-source
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

(Sorry for the German locale ....)

The error is caused by

```
Makefile:659: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
CFG80211 API is prefered for this kernel version
```

The reason for this is, that trusty ships gcc 4.8.x which doesn't support fstack-protector-strong.

As a workaround I instlled gcc-4.9.2 on trusty like descrived here: http://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu

But I have still no clue, why the compile run worked with 4.2.3 / gcc 4.8.x.

Can that be fixed in the Makefile of bcmwl-ubuntu ?

rgds,
j

**Comment by longsleep** [comment]
Hi, this is not something this driver can fix. Seems like 4.2.5-wily requires gcc 4.9 from wily does no longer compile with gcc 4.8 (wily has 4.9 and 5.2)
