### ISSUE TITLE
New version of driver

### ISSUE THREAD

**Issue by ricoli** [longsleep/bcmwl-ubuntu#13]
According to http://www.broadcom.com/support/?gid=1 there's a new version of the driver (6.30.223.271), would it be possible to get a new version of the package with it?

**Comment by longsleep** [comment]
Imported in 851574a993577c15db637ff1f40699a8f6b0c26f - currently untested, the new version probably needs some fixes to the patches.

**Comment by longsleep** [comment]
Patches were cleaned up in e6f8da5b16a3c5e47f15e34c7066773b8af3e870 - It seems to compile fine for me - please build the package yourself and let me know if the new version works for you before i update the ppa.

**Comment by s7dhansh** [comment]
I tried to compile but got this error:

gbp:warning: Pristine-tar branch "pristine-tar" not found
gbp:error: Pristine-tar couldn't checkout "bcmwl_6.30.223.271+bdcom.orig.tar.gz": pristine-tar: no pristine-tar branch found, use "pristine-tar commit" first

Couldn't find much from google. Can you please help?

**Comment by longsleep** [comment]
Sorry, seems like i have removed the pristine-tar branch. I just added it back. If you still get errors, make sure to have pulled the pristine-tar and upstream remote branches as well.

**Comment by s7dhansh** [comment]
So far so good. Working fine with 4.3rc7. I guess it will work nicely with others too.

**Comment by ricoli** [comment]
I got this while building (using kernel 3.13.0-67-generic):

```
ricardo@ricardo-XPS-13-9343:~/bcmwl-ubuntu/bcmwl-ubuntu-master$ gbp buildpackage -b -uc -us
 dpkg-buildpackage -rfakeroot -D -us -uc -i -I -b
dpkg-buildpackage: source package bcmwl
dpkg-buildpackage: source version 6.30.223.271+bdcom-1longsleep0
dpkg-buildpackage: source distribution wily
dpkg-buildpackage: source changed by Simon Eisenmann <simon@longsleep.org>
 dpkg-source -i -I --before-build bcmwl-ubuntu-master
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 7.0.50~) dh-modaliases
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I -b failed
gbp:error: Couldn't run 'debuild -i -I -b -uc -us': debuild -i -I returned 29
```

**Comment by s7dhansh** [comment]
sudo apt-get install git git-buildpackage pristine-tar build-essential dh-modaliases debhelper

@ricoli use the above to installs deps

**Comment by ricoli** [comment]
thank you very much @s7dhansh and @longsleep, it built and installed with success. Working well so far :)

**Comment by longsleep** [comment]
Cool thanks for confirming. Will push a release to the ppa tonight and then close this issue.

**Comment by derjohn** [comment]
\o/\o/\o/\o/ Thx !

**Comment by longsleep** [comment]
The ppa was updated for wily, vivid and trusty. See https://launchpad.net/~longsleep/+archive/ubuntu/bcmwl
