### ISSUE TITLE
Kernel 4.4 error, not supported 

### ISSUE THREAD

**Issue by huizache** [longsleep/bcmwl-ubuntu#14]
I get the following error when following instructions with new kernel 4.4 and ubuntu 14.04

DKMS make.log for bcmwl-6.30.223.271+bdcom for kernel 4.4.0-040400-generic (x86_64)
mar ene 12 22:09:35 CST 2016
make: se ingresa al directorio «/usr/src/linux-headers-4.4.0-040400-generic»
Makefile:660: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/built-in.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.o
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
make[1]: **\* [/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.o] Error 1
make: **\* [_module_/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build] Error 2
make: se sale del directorio «/usr/src/linux-headers-4.4.0-040400-generic»

**Comment by derjohn** [comment]
@huizache I didn't check with 4.4 yet, but the error indicates the same problem I had some time ago. The reason was not the driver, but an too-old gcc compiler.

See here: https://github.com/longsleep/bcmwl-ubuntu/issues/12 ... This way you can workaround the issue.

**Comment by huizache** [comment]
@derjohn thank you for the information.

**Comment by huizache** [comment]
and thank you @longsleep for your work.
