### ISSUE TITLE
Kernel 4.5 and 4.6 support

### ISSUE THREAD

**Issue by derjohn** [longsleep/bcmwl-ubuntu#15]
Hello,
I am using the driver for kernel 4.4.9 (ubuntu PPA, lowlatency) and it works quite well.
I can build the driver for kernel 4.5.x adn 4.6.x (ubuntu PPA, lowlatency), but with those kernels the Wifi-Connections are not stable (no traffic seen und strange errror message about wrong mac address, which I've never seen before).

This might be the wrong place to report those issues, but are you guys using the driver with 4.5 and 4.6 ? I run a rmbp retina 15",  14e4:43a0 (rev 03)

rgds,
j

**Comment by iAnatoly** [comment]
I am using 6.30.223.271+bdcom-1longsleep0 with 4.6.0 on Ubuntu 16.04 LTS. Hardware is Dell XPS 9343, and it appears to be working fine (I've jumped on vanilla 4.6.0 out of curiosity after seeing your post).

**Comment by longsleep** [comment]
Well if the driver compiles all issues with it are owned by Broadcom. You should report it there.
