### ISSUE TITLE
4.7 kernel error

### ISSUE THREAD

**Issue by s7dhansh** [longsleep/bcmwl-ubuntu#17]
```
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c: In function ‘wl_update_wiphybands’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:2888:15: error: array subscript is not an integer
   wiphy->bands[IEEE80211_BAND_5GHZ] = &__wl_band_5ghz_n;

```

Can you help me fix this? @longsleep

**Comment by longsleep** [comment]
Not really - looks like 4.7 patches are required.

**Comment by VGerris** [comment]
I made a pull request to fix this:
https://github.com/longsleep/bcmwl-ubuntu/pull/18
Tested on 4.7 and 4.6, not on older ones. 
Maybe good to try that and not break compatibility, in that case maybe add an if-else for the kernel version.

**Comment by longsleep** [comment]
See #18
