### ISSUE TITLE
.deb packages don't appear to work with kernel 4.1.rc1

### ISSUE THREAD

**Issue by glarue** [longsleep/bcmwl-ubuntu#2]
First, thank you for your work on this - it's great to have a resource for hardware this new!

I've installed the mainline 4.1.rc1 kernel - which has the advantage of having all of the audio bugs fixed -  but the .deb bcmwl files you so kindly supplied don't appear to work for that version. They work fine for the 3.19.5 kernel on the same system, however. Hoping maybe it's something obvious that you could tweak? Many thanks!

**Comment by kenjungclaus** [comment]
Have you tried building the package yourself like described in the readme? Which error message do you get now (when doing what)?

**Comment by longsleep** [comment]
I guess 4.1 needs another set of patches. Please post your DKMS build log where we can see the error.

**Comment by glarue** [comment]
Thanks for the responses. I really shouldn't have posted this without doing more due diligence to troubleshoot the issue first.

I didn't actually build the kernel myself for 4.1, I just used the .deb files. As such, there wasn't an error message - wifi just doesn't work. At any rate, when I have time I'll muck around with the proper build process and see how that goes.

I'll close this now; thanks again and my apologies for the half-cocked inquiry.

**Comment by longsleep** [comment]
Deb files from launchpad? Should be fine - when installing it builds - post that log please. It tells you where to find it too.

**Comment by glarue** [comment]
I used your ppa to install the deb files - can you point me to the probable location of the log? I'm happy to help troubleshoot if I've got it.

**Comment by LeBrad** [comment]
I'm also using kernel 4.1, and I built the package myself as described in the readme. Here's the DKMS error log:

DKMS make.log for bcmwl-6.30.223.248+bdcom for kernel 4.1.0-040100rc1-generic (x86_64)
Wed Apr 29 06:14:24 BST 2015
make: Entering directory '/usr/src/linux-headers-4.1.0-040100rc1-generic'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/built-in.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_linux.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_iw.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o
  LD [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/wl.o
  Building modules, stage 2.
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  MODPOST 1 modules
FATAL: modpost: GPL-incompatible module wl.ko uses GPL-only symbol 'cpu_tss'
scripts/Makefile.modpost:90: recipe for target '__modpost' failed
make[1]: **\* [__modpost] Error 1
Makefile:1386: recipe for target 'modules' failed
make: **\* [modules] Error 2
make: Leaving directory '/usr/src/linux-headers-4.1.0-040100rc1-generic'

**Comment by longsleep** [comment]
I guess this is caused by https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=24933b82c0d9a711475a5ef7904eb733f561e637 and just an accident.

**Comment by longsleep** [comment]
Well as a fix for the problem does not seem obvious you could hack the patches and tag your locally built version as GPL. This should fix the issue - doing so for your local version is perfectly fine. You just cannot distribute that.

Change debian/patches/0001-MODULE_LICENSE.patch to declare the license to GPL and rebuild the debian package and install your locally built version.

**Comment by LeBrad** [comment]
Thanks Longsleep, that worked. Problem solved!

**Comment by longsleep** [comment]
The problem will go away with 4.1-rc3. See https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=de71ad2c97862eae1516aa36528cc3b317c17b2f for the fix in the Kernel. Please reopen when you still see this again.
