### ISSUE TITLE
This driver causes soft lockup with 4.9 kernel when trying to connect.

### ISSUE THREAD

**Issue by Magicloud** [longsleep/bcmwl-ubuntu#20]
I could not provide any information since when lock up, the machine was practically frozen.
After upgrading to 4.9 kernel, my laptop just died when I was trying to login after boot. After disabled X, I saw a lot of kernel tracks with wl and soft lockup in them.
Then I disabled the module and everything worked quite fine. I enabled the module again but did not let NetworkManger to connect. It seemed fine. Finally I tried to connect to wireless network and my laptop died in like 30 secs.

**Comment by longsleep** [comment]
Where did you get the driver from? I do not have a matching hardware anymore - try the DKMS packaging at https://github.com/tseliot/bcmwl which is newer than mine.

**Comment by Magicloud** [comment]
Thanks.
