### ISSUE TITLE
git public access?

### ISSUE THREAD

**Issue by d4vid1** [longsleep/bcmwl-ubuntu#3]
git clone git@github.com:longsleep/bcmwl-ubuntu.git bcmwl-ubuntu-master
Klone nach 'bcmwl-ubuntu-master'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by longsleep** [comment]
You cannot clone with ssh. Clone from http url or fork it if you want ssh access.

**Comment by chili555** [comment]
Your README suggests the access d4vid1 used above and it doesn't work. I suggest the README be changed to read:

```
git clone https://github.com/longsleep/bcmwl-ubuntu.git
```

**Comment by longsleep** [comment]
Good point - i changed the README

**Comment by chili555** [comment]
Awesome! Thanks.
