### ISSUE TITLE
gbp buildpackage -b -uc -us [problem]

### ISSUE THREAD

**Issue by draft1** [longsleep/bcmwl-ubuntu#5]
$ gbp buildpackage -b -uc -us
gbp:warning: Pristine-tar branch "pristine-tar" not found
pristine-tar: successfully generated /home/dan/bcmwl-ubuntu/bcmwl_6.30.223.248+bdcom.orig.tar.gz
 dpkg-buildpackage -rfakeroot -D -us -uc -i -I -b
dpkg-buildpackage: source package bcmwl
dpkg-buildpackage: source version 6.30.223.248+bdcom-1longsleep0
dpkg-buildpackage: source distribution utopic
dpkg-buildpackage: source changed by Simon Eisenmann simon@longsleep.org
 dpkg-source -i -I --before-build bcmwl-ubuntu-master
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 7.0.50~) dh-modaliases
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc -i -I -b failed
gbp:error: 'debuild -i -I -b -uc -us' failed: it exited with 29

**Comment by draft1** [comment]
This is on Ubuntu 15.04 64 bit

**Comment by longsleep** [comment]
You have to install the build dependencies
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 7.0.50~) dh-modaliases

You can also simply use my pre-built packages from https://launchpad.net/~longsleep/+archive/ubuntu/bcmwl

**Comment by draft1** [comment]
WOW, that PPA is awesome.

Going to use it, but got this:

sudo add-apt-repository ppa:longsleep/bcmwl
sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y 
sudo apt-get autoremove --purge -y && sudo apt-get autoclean -y
sudo apt-get install bcmwl
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package bcmwl

**Comment by longsleep** [comment]
You have to install bcmwl-kernel-source - bcmwl is the name of the source.

**Comment by draft1** [comment]
$ sudo apt-get install bcmwl-kernel-source
Reading package lists... Done
Building dependency tree  
Reading state information... Done
bcmwl-kernel-source is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

So I do: sudo apt-get install --reinstall bcmwl-kernel-source?

**Comment by longsleep** [comment]
Well what version do you have? Make sure you have the one from the ppa and that it built fine for your kernel - reboot and you are ready to go.

**Comment by draft1** [comment]
I have the version from your repo here.
Just managed to install it after I created this issue.

**Comment by longsleep** [comment]
What is the problem then?

**Comment by draft1** [comment]
Previous problem is on 1st post, but forgot to update this before you posted an answer.
Now I want to switch directly to your repo :).

With thiss command:
sudo apt-get install --reinstall bcmwl-kernel-source

Already sufficient?

Thanks!

**Comment by draft1** [comment]
I mean the PPA not building from source.

**Comment by longsleep** [comment]
Yes - bcmwl-kernel-source gives you the driver and is all you need. Note that you only need my version when you have kernel 4.0 or later. Stock version from Ubuntu is OK if you use stock kernel.

**Comment by draft1** [comment]
I'm on Ubuntu 15.04 64bit
Kernel 4.0.5

I just issued this just to be sure I'm using your packages:
sudo apt-get purge bcmwl-kernel-source
sudo apt-get install bcmwl-kernel-source
sudo update-initramfs -u
sudo update-grub

**Comment by draft1** [comment]
You can closed this now :)
Thanks a lot for the PPA.

**Comment by longsleep** [comment]
Sounds good - on installation it builds for your kernel. That would fail for 4.0 if you hadn't the patched version.

**Comment by draft1** [comment]
Seems it install fine?

$ sudo apt-get install bcmwl-kernel-source
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following NEW packages will be installed:
  bcmwl-kernel-source
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,518 kB of archives.
After this operation, 8,042 kB of additional disk space will be used.
Selecting previously unselected package bcmwl-kernel-source.
(Reading database ... 230748 files and directories currently installed.)
Preparing to unpack .../bcmwl-kernel-source_6.30.223.248+bdcom-1longsleep0_amd64.deb ...
Unpacking bcmwl-kernel-source (6.30.223.248+bdcom-1longsleep0) ...
Setting up bcmwl-kernel-source (6.30.223.248+bdcom-1longsleep0) ...
Loading new bcmwl-6.30.223.248+bdcom DKMS files...
First Installation: checking all kernels...
Building only for 4.0.5-040005-generic
Building for architecture x86_64
Building initial module for 4.0.5-040005-generic
Done.

wl:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/4.0.5-040005-generic/updates/dkms/

depmod....

DKMS: install completed.
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.103ubuntu15) ...
update-initramfs: Generating /boot/initrd.img-4.0.5-040005-generic

**Comment by inceabdullah** [comment]
`DKMS make.log for bcmwl-6.30.223.271+bdcom for kernel 4.19.0-kali4-amd64 (x86_64)
Fri 03 May 2019 01:16:33 PM +03
make: Entering directory '/usr/src/linux-headers-4.19.0-kali4-amd64'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.o
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c: In function ‘osl_os_get_image_block’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c:1079:28: warning: passing argument 2 of ‘kernel_read’ makes pointer from integer without a cast [-Wint-conversion]
  rdlen = kernel_read(fp, fp->f_pos, buf, len);
                          ~~^~~~~~~
In file included from /usr/src/linux-headers-4.19.0-kali4-common/include/linux/huge_mm.h:8,
                 from /usr/src/linux-headers-4.19.0-kali4-common/include/linux/mm.h:499,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:65,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c:25:
/usr/src/linux-headers-4.19.0-kali4-common/include/linux/fs.h:2888:43: note: expected ‘void *’ but argument is of type ‘loff_t’ {aka ‘long long int’}
 extern ssize_t kernel_read(struct file *, void *, size_t, loff_t *);
                                           ^~~~~~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c:1079:37: warning: passing argument 3 of ‘kernel_read’ makes integer from pointer without a cast [-Wint-conversion]
  rdlen = kernel_read(fp, fp->f_pos, buf, len);
                                     ^~~
In file included from /usr/src/linux-headers-4.19.0-kali4-common/include/linux/huge_mm.h:8,
                 from /usr/src/linux-headers-4.19.0-kali4-common/include/linux/mm.h:499,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:65,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c:25:
/usr/src/linux-headers-4.19.0-kali4-common/include/linux/fs.h:2888:51: note: expected ‘size_t’ {aka ‘long unsigned int’} but argument is of type ‘char *’
 extern ssize_t kernel_read(struct file *, void *, size_t, loff_t *);
                                                   ^~~~~~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c:1079:42: warning: passing argument 4 of ‘kernel_read’ makes pointer from integer without a cast [-Wint-conversion]
  rdlen = kernel_read(fp, fp->f_pos, buf, len);
                                          ^~~
In file included from /usr/src/linux-headers-4.19.0-kali4-common/include/linux/huge_mm.h:8,
                 from /usr/src/linux-headers-4.19.0-kali4-common/include/linux/mm.h:499,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:65,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.c:25:
/usr/src/linux-headers-4.19.0-kali4-common/include/linux/fs.h:2888:59: note: expected ‘loff_t *’ {aka ‘long long int *’} but argument is of type ‘int’
 extern ssize_t kernel_read(struct file *, void *, size_t, loff_t *);
                                                           ^~~~~~~~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_pci_probe’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:776:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if ((val & 0x0000ff00) != 0)
  ^~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:778:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
   bar1_size = pci_resource_len(pdev, 2);
   ^~~~~~~~~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_init_timer’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:2359:2: error: implicit declaration of function ‘init_timer’; did you mean ‘init_timers’? [-Werror=implicit-function-declaration]
  init_timer(&t->timer);
  ^~~~~~~~~~
  init_timers
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:2360:10: error: ‘struct timer_list’ has no member named ‘data’
  t->timer.data = (ulong) t;
          ^
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:2361:20: error: assignment to ‘void (*)(struct timer_list *)’ from incompatible pointer type ‘void (*)(ulong)’ {aka ‘void (*)(long unsigned int)’} [-Werror=incompatible-pointer-types]
  t->timer.function = wl_timer;
                    ^
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_monitor’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:2922:10: error: ‘struct net_device’ has no member named ‘last_rx’
  skb->dev->last_rx = jiffies;
          ^~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-4.19.0-kali4-common/scripts/Makefile.build:308: /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/usr/src/linux-headers-4.19.0-kali4-common/Makefile:1535: _module_/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build] Error 2
make[1]: *** [Makefile:146: sub-make] Error 2
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/usr/src/linux-headers-4.19.0-kali4-amd64'
`

I have tried before patch wl_3.10.patch unf also.
