### ISSUE TITLE
Kernel 4.2 fix

### ISSUE THREAD

**Issue by s7dhansh** [longsleep/bcmwl-ubuntu#6]
Can you please add this fix?

https://gist.github.com/boesing/ae0777c0095a1d8d317f

Thank you.

**Comment by longsleep** [comment]
Please try branch `linux-4.2` and let me know if that works for you.

**Comment by s7dhansh** [comment]
Hey, thanks for replying.
The 4.2 has another issue related to 'workqueue'  due to which bcmwl
installation fails even after fixing the cfg function issue.
For fixing that, I need to compile the kernel after applying a patch. Not
getting enough time these days. Once I am free will try it definitely.

**Comment by longsleep** [comment]
I guess you mean 

```
FATAL: modpost: GPL-incompatible module wl.ko uses GPL-only symbol 'flush_workqueue'
scripts/Makefile.modpost:90: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1
Makefile:1389: recipe for target 'modules' failed
make: *** [modules] Error 2
```

You can workaround this, by changing the module license to GPL in https://github.com/longsleep/bcmwl-ubuntu/blob/master/debian/patches/0001-MODULE_LICENSE.patch before you build the debian package. No need to compile the Kernel. Just make sure to report this to the Kernel developers so they can make the symbol available for non-GPL modules.

**Comment by s7dhansh** [comment]
Yes.
Oh Thanks. I did it. The kernel was installed successfully. Thank you.

## 

Sudhanshu

**Comment by longsleep** [comment]
The following Kernel commit causes the GPL problem. https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/kernel/workqueue.c?id=37b1ef31a568fc02e53587620226e5f3c66454c8 - I do not see any easy way to make this work again.

**Comment by s7dhansh** [comment]
They were supposed to fix it in 4.2rc6 :
http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.2-rc6-unstable/0002-debian-changelog.patch
See the Tim Gardner fix: 'workqueue: Make flush_workqueue() available again
to non GPL modules'

But somehow it wasn't working. I did not dig much though.

I hope it will be fixed in the next releases though.

## 

Sudhanshu

**Comment by astephanh** [comment]
Hi, running on MacBookAir7,1 the shutdown always crashes the kernel with null pointer dereference error.

**Comment by longsleep** [comment]
@s7dhansh - well that fix is in the ubuntu mainline builds, but has not been merged into the 4.2 kernel tree (see https://lkml.org/lkml/2015/8/4/802)
@astephanh  - how does that relate to this issue?

**Comment by longsleep** [comment]
Should that patch be applied to the 4.2 tree, the bcmwl will need another fix at https://github.com/longsleep/bcmwl-ubuntu/blob/80acd1621df2dc0c31914bbe5570e786f8cbb2be/src/src/include/linuxver.h#L94 so it calls flush_workqueue directly.

**Comment by jbtrystram** [comment]
Hello, 

the linux-4.2 branch compile successfully (after installing dh-modaliases and debhelper packages). however, i can't install the deb package : 

Building initial module for 4.2.0-040200-generic
ERROR (dkms apport): kernel package linux-headers-4.2.0-040200-generic is not supported
Error! Bad return status for module build on kernel: 4.2.0-040200-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
modprobe: FATAL: Module wl not found.

any idea ?

**Comment by longsleep** [comment]
Well look into /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log - that should have all the ugly details.

**Comment by jbtrystram** [comment]
FATAL: modpost: GPL-incompatible module wl.ko uses GPL-only symbol 'flush_workqueue'

I see in the preview link you posted that is supposed to be done in 4.3 ? 
No wifi until then ?:(

**Comment by longsleep** [comment]
@jbtrystram Well - if you compile yourself you can fix it by declaring this module a GPL module - see https://github.com/longsleep/bcmwl-ubuntu/issues/6#issuecomment-129772346

**Comment by jbtrystram** [comment]
changed to +MODULE_LICENSE("GPL"); in debian/patches/0001-MODULE-LISCENCE.patch
i have the same error when compliling :(

**Comment by longsleep** [comment]
@jbtrystram: Well then you did something wrong. Note that you need to rebuild the debian package and then install the newly built one. Check your change and make sure the changed file is in your installed Debian package.

**Comment by jbtrystram** [comment]
Works indeed :)
Was having some git-related issues.
Thanks for this awesome works and your help !

**Comment by longsleep** [comment]
I merged the 4.2 support. Note that the mainline kernel still has not allowed flush_workqueue to be used from non GPL Kernels. The Ubuntu 4.2 Kernel has the patch locally though.

**Comment by longsleep** [comment]
If you use Ubuntu 15.10 with Kernel 4.2 you no longer need my patched version. For older Ubuntu versions you can install the Ubuntu mainline Kernel (http://kernel.ubuntu.com/~kernel-ppa/mainline/) and use my ppa (https://launchpad.net/~longsleep/+archive/ubuntu/bcmwl) which i just updated for 15.04 and 14.04.

**Comment by longsleep** [comment]
I just saw that the fix for the license problem was merged to mainline kernel tree (see https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/kernel/workqueue.c?id=7d3e2eb1786fafa186eb8bc276edef75ba69e023) - so we can expect to have this resolved eventually.

**Comment by brunano21** [comment]
I saw that this issue is the same of mine here #10.
Any suggestion?

**Comment by edcarter** [comment]
@brunano21 I compiled the patch changing the licence to "GPL" and then hosted it on my git: https://github.com/edcarter/bcmwl-ubuntu/tree/master. The compiled binary is in the root so you can just download that and try it out.
