### ISSUE TITLE
modprobe: FATAL: Module wl not found

### ISSUE THREAD

**Issue by ericyoung** [longsleep/bcmwl-ubuntu#9]
Linux Mint 17.2. Upgraded kernel to 4.2. Having trouble getting wifi to work. I followed the build instructions and continue to get the following output:

....
Building initial module for 4.2.0-040200-generic
Error! Bad return status for module build on kernel: 4.2.0-040200-generic (x86_64)
Consult /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/make.log for more information.
modprobe: FATAL: Module wl not found.
....

make.log:

DKMS make.log for bcmwl-6.30.223.248+bdcom for kernel 4.2.0-040200-generic (x86_64)
Mon Sep  7 19:55:00 CDT 2015
make: Entering directory `/usr/src/linux-headers-4.2.0-040200-generic'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  LD      /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/built-in.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_linux.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_iw.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o
  LD [M]  /var/lib/dkms/bcmwl/6.30.223.248+bdcom/build/wl.o
  Building modules, stage 2.
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  MODPOST 1 modules
FATAL: modpost: GPL-incompatible module wl.ko uses GPL-only symbol 'flush_workqueue'
make[1]: *** [__modpost] Error 1
make: *** [modules] Error 2
make: Leaving directory`/usr/src/linux-headers-4.2.0-040200-generic'

If I apt-get install from your PPA, I get the same message.

I'm on a Yoga 3 Pro. Any help is appreciated.

**Comment by longsleep** [comment]
See https://github.com/longsleep/bcmwl-ubuntu/issues/6#issuecomment-137847711  - you seither need to use a ubuntu mainline kernel build, patch your own kernel build or patch the license of bcmw.l
